config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]
  resources :stories
  resources :users, only: [:new, :create, :show]
  root 'stories#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/story.rb
class Story < ApplicationRecord
  belongs_to :user
  validates :title, :picture, :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :email, presence: true, uniqueness: { case_sensitive: false }
    validates :name, presence: true
    has_many :stories
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    helper_method :current_user
    helper_method :logged

    protected
    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
        @user = User.new
    end

    def create
        user = User.find_by_email(params[:email])
        if user && user.authenticate(params[:password])
            session[:user_id] = user.id
            redirect_to root_path, notice: 'Logeado correctamente'
        else
            flash.now[:notice] = 'Email o password inválido'
            render action: :new
        end
    end

    def destroy
        session[:user_id] = nil
        redirect_to root_url, notice: 'Signed out successfully'
    end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
before_action :set_story, only: [:show, :edit, :update, :destroy]

    def index
        @stories = Story.all
    end

    def show
        @stories = Story.all
    end

    def new
        @story = current_user.stories.build
        
    end

    def edit
        @user = User.where(user_id: params[:id])
    end

    def create 
        @story = Story.new(story_params)
        @story.user = helpers.current_user #aca le indico al usuario de la historia es igual al usuario current user
        respond_to do |format|
            if @story.save
                format.html { redirect_to @story, notice: 'Story was successfully created.' }
            else
                format.html { render :new }
            end
        end
    end

    def update
        respond_to do |format|
            if @story.update(story_params)
                format.html { redirect_to @story, notice: "Story was successfully updated." }
            else
                format.html { render :edit }
            end
        end
    end

    def destroy
        @story.destroy
        respond_to do |format|
          format.html { redirect_to stories_url, notice: "Story was successfully destroyed." }
        end
    end
    
    private
    # Only allow a list of trusted parameters through.
    def set_story
        @story = Story.find(params[:id])
    end
    
    def story_params
      params.require(:story).permit(:title, :picture, :content)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:show]

    def show
        @user = User.find(params[:id])
        @user = User.includes(:stories).find(helpers.current_user.id)
        #incluir en User para mostrar las historios que se encuentre(con el id de cada usuario que ahora es mi current user por el metodo helper)
    end

    def new
        @user = User.new
    end

    def edit
    end

    def create
        @user = User.new(user_params)
        respond_to do |format|
            if @user.save
                session[:user_id] = @user.id #para guardar en el objeto sesion el "":user_id" es un key, y el valor es el id del usuario que se creó
                format.html { redirect_to root_path, notice: 'User was successfully created.' }
            else
                format.html { render :new }
            end
        end
    end

    private

    def user_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation)
        #los atributos que vienen en params son los que se requieren y se permiten 
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
    def logged
        if session[:user_id].nil?
            false
        else
            true
        end
    end
end

app/views/layouts/application.html.erb
<html>
  <head>
    <title>Pic Story</title>
    <%= csrf_meta_tags %>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.7/sandstone/bootstrap.min.css" rel="stylesheet" integrity="sha384-G3G7OsJCbOk1USkOY4RfeX1z27YaWrZ1YuaQ5tbuawed9IoreRDpWpTkZLXQfPm3" crossorigin="anonymous">
     <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <div class="container">
      <% flash.each do |_, value| %>
        <div><%= value %>
      <% end %>
      <% if notice %>
        <div class="alert alert-dismissible alert-success">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <h4>Información</h4>
          <p><%= notice %></p>
        </div>
      <% end %>
      <% if alert %>
        <div class="alert alert-dismissible alert-success">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <h4>Atención</h4>
          <p><%= alert %></p>
        </div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

    

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<%= root_path %>">PicStory</a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                        <i class="fa fa-user-circle-o" style="font-size:24px""></i>
                        <span class="caret"></span>
                    </a>
                    <!-- ¡Pending implementation! Should work toggling between sign_in and sign_out -->
                    <ul class="dropdown-menu">
                        <% if current_user %>
                        <li><%=link_to 'Create PicStory', new_story_path %></li>
                        <li><%=link_to 'My PicStories', stories_path %></li>
                        <li><a href="#">'My Profile'</a></li>
                        <li role="separator" class="divider"></li>
                        <li><%= link_to('Sign out', session_path(current_user), method: :delete) %></li>
                    <% else %>
                        <li><%= link_to('Sign in', new_session_path) %></li>
                        <li><%= link_to('Create new User', new_user_path) %></li>
                    <% end %>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>

app/views/stories/_form.html.erb
<%= form_with(model: story, local: true) do |form| %>
    <% if story.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(story.errors.count, "error") %> prohibited this story from being saved:</h2>

            <ul>
                <% story.errors.full_messages.each do |message| %>
                <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <div class="field">
        <%= form.label :title %>
        <%= form.text_field :title %>
    </div>

    <div class="field">
        <%= form.label :picture %>
        <%= form.text_field :picture, id: :story_picture %>
    </div>

    <div class="field">
        <%= form.label :content %>
        <%= form.text_area :content, id: :story_content %>
    </div>

    <div class="actions">
        <%= form.submit %>
    </div>
<% end %>

app/views/stories/edit.html.erb
<h1>Editing PicStory</h1>

<%= render 'form', story: @story %>

<%= link_to 'Show', @story %> |
<%= link_to 'Back', stories_path %>

app/views/stories/index.html.erb
<h2><%= current_user ? "Hola: #{current_user.name}" : 'Hola extraño, haz click en log in para registrarte' %></h2>





<div class="row">
  <div class="col-xs-8 col-sm-10 col-md-10">
    <h1>PicStories</h1>
  </div>
  <div class="col-xs-4 col-sm-2 col-md-2">
    <%= link_to 'New story', new_story_path, class: "btn btn-info btn-sm" %>
  </div>
</div>

<div class="row">
  <% @stories.reverse.each do |story| %>
    <div class="col-sm-6 col-md-4">
      <div class="thumbnail">
        <%= link_to(image_tag(story.picture), story) if story.picture? %>
        <div class="caption">
          <h3><%= story.title %></h3>
          <small><%= time_ago_in_words(story.created_at) %> ago</small>
          <p><%= story.content.truncate(150)  %></p>
          <p><%= story.user.name  %></p>
          <p><%= link_to 'Show', story, class: "btn btn-primary" %> <%= link_to 'Edit', edit_story_path(story), class: "btn btn-warning" %> <%= link_to 'Destroy', story, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></p>
        </div>
      </div>
    </div>
  <% end %>
</div>


<br>

app/views/stories/new.html.erb
<p id="notice"><%= notice %></p>

<h1>New PicStory</h1>

<%= render 'form', story: @story %>

<%= link_to 'Back', stories_path %>

app/views/stories/show.html.erb
    <div class="container">

        <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-8">
                <%= image_tag(@story.picture, style: "max-width: 100%; border-radius: 10px;") if @story.picture? %>
            </div>
            <div class="col-md-2"></div>
        </div>
        <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-8">
                <h1><%= @story.title %></h1>
                <small><%= time_ago_in_words(@story.created_at) %> ago</small>
            </div>
            <div class="col-md-2"></div>
        </div>

        <hr>
        <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-8">
                <p><%= @story.content %></p>
            </div>
            <div class="col-md-2"></div>
        </div>

        <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-8">
                <p><%= @story.user.name %></p>
            </div>
            <div class="col-md-2"></div>
        </div>

        <br>
        <div class="row">
            <div class="col-md-8"></div>
            <div class="col-md-2">
                <p><%= link_to 'Edit', edit_story_path(@story), class: "btn btn-warning btn-sm" %> 
                <%= link_to 'Back', stories_path, class: "btn btn-info btn-sm" %></p>
            </div>
            <div class="col-md-2"></div>
        </div>
    </div>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
    <% if user.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

            <ul>
                <% user.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <div class="field">
        <%= form.label :name %>
        <%= form.text_field :name %>
    </div>

    <div class="field">
        <%= form.label :email %>
        <%= form.email_field :email %>
    </div>

    <div class="field">
        <%= form.label :password %>
        <%= form.password_field :password %>
    </div>

    <div class="field">
        <%= form.label :password_confirmation %>
        <%= form.password_field :password_confirmation %>
    </div>

    <div class="actions">
        <%= form.submit %>
    </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Password </th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.password_digest %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<div class=“row”>
<div class=“col-md-3">
<h1>Registro de usuario</h1>
<%= form_with(model: @user, local: true) do |form| %>
 <% if @user.errors.any? %>
   <div id=“error_explanation”>
     <h2><%= pluralize(@user.errors.count, “error”) %> prohibited this user from being saved:</h2>

     <ul>
     <% @user.errors.full_messages.each do |message| %>
       <li><%= message %></li>
     <% end %>
     </ul>
   </div>
 <% end %>
 <div class=“form-group”>
   <%= form.label :Nombre  %>
   <%= form.text_field :name, id: :user_name, class:'form-control' %>
 </div>

 <div class=“form-group”>
   <%= form.label :email %>
   <%= form.email_field :email, id: :user_email, class:'form-control' %>
 </div>

 <div class=“form-group”>
   <%= form.label :password %>
   <%= form.password_field :password, id: :user_password, class:'form-control' %>
 </div>
<div class=“form-group”>
   <%= form.label :password_confirmation %>
   <%= form.password_field :password_confirmation, id: :user_password_confirmation , class:'form-control'%>
 </div>
 <div class=“form-group”>
   <%= form.submit class:'btn btn-success' %>
 </div>
<% end %>


</div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="col-xs-8 col-sm-10 col-md-10">
    <h1>PicStories</h1>
  </div>
  <div class="col-xs-4 col-sm-2 col-md-2">
    <%= link_to 'New story', new_story_path, class: "btn btn-info btn-sm" %>
  </div>
</div>

<div class="row">
  <% @user.stories.reverse.each do |story| %>
    <div class="col-sm-6 col-md-4">
      <div class="thumbnail">
        <%= link_to(image_tag(story.picture), story) if story.picture? %>
        <div class="caption">
          <h3><%= story.title %></h3>
          <small><%= time_ago_in_words(story.created_at) %> ago</small>
          <p><%= story.content.truncate(150)  %></p>
          <p><%= link_to 'Show', story, class: "btn btn-primary" %> <%= link_to 'Edit', edit_story_path(story), class: "btn btn-warning" %> <%= link_to 'Destroy', story, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></p>
        </div>
      </div>
    </div>
  <% end %>
</div>


<br>